export const FETCH_MOVIE_LIST_SUCCESS = 'FETCH_MOVIE_LIST_SUCCESS';
export const FETCH_MOVIE_LIST_FAILED = 'FETCH_MOVIE_LIST_FAILED';
export const ADD_MOVIE_UPLOAD_IMGAGE_SUCCESS = 'ADD_MOVIE_UPLOAD_IMGAGE_SUCCESS';

export const FETCH_MOVIE_INFO_SUCCESS = 'FETCH_MOVIE_INFO_SUCCESS';
